apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-conf
  namespace: devops
  labels:
    alicloud-pvname: sonarqube-conf
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: sonarqube-conf
    volumeAttributes:
      server: "2b7f34a121-ros26.cn-shenzhen.nas.aliyuncs.com"
      path: "/share/sonarqube/conf"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data
  namespace: devops
  labels:
    alicloud-pvname: sonarqube-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: sonarqube-data
    volumeAttributes:
      server: "2b7f34a121-ros26.cn-shenzhen.nas.aliyuncs.com"
      path: "/share/sonarqube/data"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions
  namespace: devops
  labels:
    alicloud-pvname: sonarqube-extensions
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: sonarqube-extensions
    volumeAttributes:
      server: "2b7f34a121-ros26.cn-shenzhen.nas.aliyuncs.com"
      path: "/share/sonarqube/extensions"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-logs
  namespace: devops
  labels:
    alicloud-pvname: sonarqube-logs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: sonarqube-logs
    volumeAttributes:
      server: "2b7f34a121-ros26.cn-shenzhen.nas.aliyuncs.com"
      path: "/share/sonarqube/logs"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3