apiVersion: v1
kind: ConfigMap
metadata:
  namespace: devops
  name: drone-server
data:
  drone-server-proto: http
  drone-open: "true"
  drone-server-host: drone-server.devops.svc.cluster.local
  drone-server-port: ":80"
  drone-debug: "true"
  drone-logs-trace: "true"
  drone-git-always-auth: "false"
  drone-gogs: "true"
  drone-gogs-skip-verify: "true"
  drone-gogs-server: http://git.devops.svc.cluster.local:3000
  drone-provider: gogs
  drone-rpc-secret: 7b4eb5caee376cf81a2fcf7181e66175
  drone-user-create: username:samego,admin:true
  drone-database-driver: postgres
  drone-database-source: postgresql://admin:devops@postgres.devops.svc.cluster.local:5432/drone?sslmode=disable