kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-server-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      alicloud-pvname: drone-server-data

