apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-server-data
  namespace: devops
  labels:
    alicloud-pvname: drone-server-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: drone-server-data
    volumeAttributes:
      server: "2b7f34a121-ros26.cn-shenzhen.nas.aliyuncs.com"
      path: "/share/drone-server/data"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3

