apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: devops
  labels:
    alicloud-pvname: postgres-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: postgres-data
    volumeAttributes:
      server: "2b7f34a121-ros26.cn-shenzhen.nas.aliyuncs.com"
      path: "/share/postgres/data"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3
