kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: postgres-data
