apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: devops
spec:
  ports:
  - name: postgressql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
