kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: git-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      alicloud-pvname: git-data

